# -*- coding: utf-8 -*-
"""health.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mVK1YGbXypRn7OG8NKRfd39LCBO2dUSW
"""

import streamlit as st
import requests

st.set_page_config(page_title="Advanced Healthcare Symptom Checker", layout="centered")
st.title("🩺 AI Health Advisor (Long Form)")
st.markdown("Enter your symptoms and get a **detailed** AI response.")

OPENROUTER_API_KEY = st.secrets["OPENROUTER_API_KEY"]

user_input = st.text_area("Describe your symptoms here:")

if st.button("Check Now"):
    if not user_input.strip():
        st.warning("Please enter your symptoms.")
    else:
        with st.spinner("Analyzing..."):
            try:
                url = "https://openrouter.ai/api/v1/chat/completions"
                headers = {
                    "Authorization": f"Bearer {OPENROUTER_API_KEY}",
                    "Content-Type": "application/json"
                }
                data = {
                    "model": "meta-llama/llama-2-13b-chat",
                    "messages": [
                        {
                            "role": "system",
                            "content": (
                                "You're a helpful virtual health assistant. You provide general wellness guidance and explain what symptoms might indicate. "
            "**Do not suggest or name any medications or treatments.** Always remind users to consult a licensed healthcare professional."
                            )
                        },
                        {
                            "role": "user",
                            "content": f"My symptoms are: {user_input}"
                        }
                    ],
                    "temperature": 0.7
                }
                response = requests.post(url, headers=headers, json=data)
                result = response.json()
                output = result["choices"][0]["message"]["content"]


if any(word in output.lower() for word in banned_words):
    st.warning("⚠️ This response mentioned medication, which is not allowed in this app. Please consult a healthcare provider.")
else:
    st.success("Here’s what I found:")
    st.write(output)

                st.success("Here’s what I found:")
                st.write(output)

            except Exception as e:
                st.error(f"An error occurred: {e}")